{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "qzhao-v1-log.serviceAccountName" . }}
  labels:
{{ include "qzhao-v1-log.labels" . | indent 4 }}
{{- end -}}
